#!/bin/bash
# Setup GitHub Repository
# This script helps you create and push to a GitHub repository

echo "🔧 GitHub Setup for auto_instrumentation"
echo ""
echo "Your git config is now set to:"
echo "  Username: earthmancash2"
echo "  Email: chetanvsharma@gmail.com"
echo ""
echo "📋 To create a GitHub repository and push your code:"
echo ""
echo "1️⃣  Go to: https://github.com/new"
echo "   - Repository name: auto_instrumentation"
echo "   - Description: Marketplace test harness for auto-instrumentation tools"
echo "   - Keep it Public (or Private if you prefer)"
echo "   - DON'T initialize with README (we already have one)"
echo ""
echo "2️⃣  After creating the repo, run these commands:"
echo ""
echo "   git remote add origin git@github.com:earthmancash2/auto_instrumentation.git"
echo "   git push -u origin main"
echo "   git push origin instrumented"
echo "   git push --tags"
echo ""
echo "3️⃣  View your repository at:"
echo "   https://github.com/earthmancash2/auto_instrumentation"
echo ""
echo "💡 You can also use HTTPS instead of SSH:"
echo "   git remote add origin https://github.com/earthmancash2/auto_instrumentation.git"
echo ""
